[project]
name = "repl-nix-telegram-summary-bot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.51.2",
    "telethon>=1.37.0",
]
